### PR TITLE
Correction of author information

### PR DESCRIPTION
**Pull request by lsvih**
Dear Sir:
Here is a correction of author information.
I ensure that nothing else was modified and meta-data was not changed.

### CODE REVIEW

**Review by lawrennd — COMMENTED** [review]
This seems to be adding a new affiliation to an author. Can you confirm when the affiliation changed?

**Comment by lsvih** [comment]
@lawrennd Yes I have double-checked it

**Review by lawrennd — COMMENTED** [review]
This seems to be adding a new affiliation to an author. 

Can you confirm when the affiliation changed?

**Comment by lsvih** [comment]
Yes, I can confirm it.

**Review by lawrennd — APPROVED** [review]
Approval change of affiliation.

**Comment by lsvih** [comment]
Your support is greatly appreciated 😃

**Pull request merged**
